### ISSUE TITLE
Adding bans to HD Admin Commands

### ISSUE THREAD

**Issue by ghost** [ForeverhdRBX/HDAdmin#1]
I don't know if it's the good place to write this as I don't know where to write for this type of request.

I have a roblox server with Kolh's Admin Infinite (KAI). This was a good admin command but there was a glitch in my server : sometimes, it teleported me to "game loader" by lbp3fans. I created another server to test each item. I deleted KAI and this bug was gone... So I changed to HD Admin Commands (which is very good by the way!) but I had bans in my server with KAI. I want to add them to the HD Admin Commands banland but you cannot do it from the game if they are not connected. So I tried to add them inside the script. The problem is : I don't know how to write it! I wrote the nicknames and Ids realted to their accounts but not working...

So, this is not a security issue or else but... Can you help me?

**Comment by 1ForeverHD** [comment]
Good spot. If you've added them in via the Banned setting in the Settings module then this will work, I've just forget to register these users under the ban menu in-game. I'll fix this for you shortly.

**Comment by 1ForeverHD** [comment]
Bans via the settings are now displayed:

![image%50](https://user-images.githubusercontent.com/51117782/61582496-985dcd00-ab23-11e9-97bc-81475afb5bf0.png)

![image](https://user-images.githubusercontent.com/51117782/61582501-a4e22580-ab23-11e9-988b-e55564b1575f.png)
